# Generated by Django 5.1.1 on 2024-09-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_profile_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cover_images',
            new_name='cover_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
