# Generated by Django 5.1.1 on 2024-09-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_rename_address_profile_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
