# Generated by Django 5.1.1 on 2024-09-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adress',
            new_name='address',
        ),
    ]
