# Generated by Django 5.1.1 on 2024-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_photo_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_book',
            field=models.ImageField(blank=True, default='book.jpg', null=True, upload_to='photos_books'),
        ),
    ]
